# Generated by Django 5.2.17 on 2026-09-11 19:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_attachment_internalnote_notification_quote_quoteitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=10000)),
                ('from_team', models.BooleanField(default=False)),
                ('client_nonce', models.UUIDField(default=uuid.uuid4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='direct_messages', to='core.organization')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['organization', 'id'], name='core_direct_organiz_c698e9_idx')],
                'constraints': [models.UniqueConstraint(fields=('author', 'client_nonce'), name='unique_direct_message_send')],
            },
        ),
    ]
