# Generated by Django 5.2.17 on 2026-09-12 10:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_directmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('PAID', 'Payée'), ('PREPARING', 'En préparation'), ('READY_FOR_PICKUP', 'Prête'), ('SHIPPED', 'Expédiée'), ('DELIVERED', 'Livrée'), ('CANCELLED', 'Annulée'), ('REFUNDED', 'Remboursée')], default='PENDING', max_length=20)),
                ('total_cents', models.PositiveIntegerField()),
                ('credits_cents', models.PositiveIntegerField()),
                ('shipping_cents', models.PositiveIntegerField()),
                ('shipping_address', models.TextField(max_length=1500)),
                ('idempotency_key', models.UUIDField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('reason', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='core.order')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(max_length=4000)),
                ('amount_cents', models.PositiveIntegerField()),
                ('credits_cents', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('SENT', 'Envoyée'), ('VIEWED', 'Vue'), ('PAID', 'Payée'), ('EXPIRED', 'Expirée'), ('CANCELLED', 'Annulée')], default='DRAFT', max_length=12)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(null=True)),
                ('viewed_at', models.DateTimeField(null=True)),
                ('paid_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('message', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.directmessage')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.project')),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.quote')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=12)),
                ('reason', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='core.paymentrequest')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('sku', models.CharField(max_length=80, unique=True)),
                ('short_description', models.CharField(max_length=400)),
                ('description', models.TextField(blank=True, max_length=10000)),
                ('price_cents', models.PositiveIntegerField()),
                ('credits_cents', models.PositiveIntegerField()),
                ('tax_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('shipping_cents', models.PositiveIntegerField(default=0)),
                ('stock_tracking_enabled', models.BooleanField(default=True)),
                ('stock_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('low_stock_threshold', models.PositiveIntegerField(default=2)),
                ('availability', models.CharField(choices=[('AVAILABLE', 'Disponible'), ('UNAVAILABLE', 'Indisponible'), ('PREORDER', 'Précommande')], default='UNAVAILABLE', max_length=16)),
                ('preorder_enabled', models.BooleanField(default=False)),
                ('purchase_with_credits_enabled', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('PUBLISHED', 'Publié'), ('ARCHIVED', 'Archivé')], default='DRAFT', max_length=12)),
                ('featured', models.BooleanField(default=False)),
                ('features', models.JSONField(blank=True, default=dict)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.category')),
            ],
            options={
                'ordering': ['-featured', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('sku', models.CharField(max_length=80)),
                ('quantity', models.PositiveIntegerField()),
                ('price_cents', models.PositiveIntegerField()),
                ('credits_cents', models.PositiveIntegerField()),
                ('tax_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('stock_decremented', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='core.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('storage_name', models.CharField(max_length=100, unique=True)),
                ('alt', models.CharField(max_length=240)),
                ('position', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', to='core.product')),
            ],
            options={
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShopEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('reference', models.CharField(max_length=80)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Actif'), ('FROZEN', 'Suspendu')], default='ACTIVE', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='CreditTopup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_cents', models.PositiveIntegerField()),
                ('status', models.CharField(default='UNAVAILABLE', max_length=20)),
                ('provider_reference', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('TOPUP', 'Recharge'), ('ADJUSTMENT', 'Correction'), ('PURCHASE', 'Achat'), ('SERVICE', 'Prestation'), ('REFUND', 'Remboursement')], max_length=12)),
                ('amount_cents', models.BigIntegerField()),
                ('status', models.CharField(default='POSTED', editable=False, max_length=10)),
                ('reference_type', models.CharField(max_length=30)),
                ('reference_id', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=500)),
                ('idempotency_key', models.CharField(max_length=160, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('reversal_of', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='core.wallettransaction')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='core.wallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='debit',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.wallettransaction'),
        ),
        migrations.AddField(
            model_name='order',
            name='debit',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.wallettransaction'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('price_cents__gt', 0), ('credits_cents__gt', 0)), name='product_positive_price'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('tax_percent__gte', 0), ('tax_percent__lte', 100)), name='product_valid_tax'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('stock_tracking_enabled', False), ('stock_quantity__isnull', False), _connector='OR'), name='product_tracked_quantity'),
        ),
        migrations.AddConstraint(
            model_name='wallettransaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount_cents', 0), _negated=True), name='ledger_nonzero'),
        ),
        migrations.AddConstraint(
            model_name='wallettransaction',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'POSTED')), name='ledger_posted'),
        ),
        migrations.AddConstraint(
            model_name='paymentrequest',
            constraint=models.CheckConstraint(condition=models.Q(('amount_cents__gt', 0), ('credits_cents__gt', 0)), name='payment_positive'),
        ),
    ]
