# Generated by Django 5.2.17 on 2026-09-12 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_immutable_commercial_history'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'permissions': [('refund_order', 'Rembourser une commande')]},
        ),
        migrations.AlterModelOptions(
            name='paymentrequest',
            options={'ordering': ['-created_at'], 'permissions': [('cancel_paymentrequest', 'Annuler une demande de paiement')]},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-featured', 'name'], 'permissions': [('publish_product', 'Publier les articles'), ('archive_product', 'Archiver les articles')]},
        ),
        migrations.AlterModelOptions(
            name='wallet',
            options={'permissions': [('adjust_wallet', 'Créer une écriture de correction du portefeuille')]},
        ),
    ]
