from django.urls import path
from . import shop as s

urlpatterns = [
    path('api/catalogue/',s.catalogue_api,name='shop-api'),
    path('catalogue/images/<uuid:pk>/',s.photo,name='shop-image'),
    path('catalogue/',s.catalogue,name='shop-catalogue'),
    path('catalogue/<slug:slug>/',s.product_detail,name='shop-product'),
    path('panier/',s.cart,name='shop-cart'),
    path('panier/vider/',s.clear_cart,name='shop-cart-clear'),
    path('panier/article/<uuid:pk>/',s.cart_add,name='shop-cart-add'),
    path('commandes/',s.orders,name='shop-orders'),
    path('commandes/<uuid:pk>/',s.order_detail,name='shop-order'),
    path('commandes/<uuid:pk>/etat/',s.order_change,name='shop-order-change'),
    path('credits/',s.wallet_view,name='shop-wallet'),
    path('credits/ajouter/',s.topup,name='shop-topup'),
    path('credits/ecriture/<uuid:pk>/',s.entry_detail,name='shop-entry'),
    path('paiements/',s.payments,name='shop-payments'),
    path('paiements/<uuid:pk>/',s.payment_detail,name='shop-payment'),
    path('paiements/<uuid:pk>/payer/',s.payment_pay,name='shop-payment-pay'),
    path('paiements/<uuid:pk>/gestion/',s.payment_manage,name='shop-payment-manage'),
    path('admin/clients/<uuid:pk>/credits/',s.wallet_view,name='shop-client-wallet'),
    path('admin/clients/<uuid:pk>/credits/ajuster/',s.wallet_adjust,name='shop-wallet-adjust'),
    path('admin/clients/<uuid:pk>/paiement/',s.payment_new,name='shop-payment-new'),
    path('admin/boutique/',s.admin_products,name='shop-admin'),
    path('admin/boutique/nouveau/',s.product_edit,name='shop-product-new'),
    path('admin/boutique/categories/',s.categories,name='shop-categories'),
    path('admin/boutique/categories/<int:pk>/',s.categories,name='shop-category-edit'),
    path('admin/boutique/<uuid:pk>/',s.product_edit,name='shop-product-edit'),
    path('admin/boutique/<uuid:pk>/action/',s.product_action,name='shop-product-action'),
    path('admin/boutique/<uuid:pk>/apercu/',s.product_preview,name='shop-product-preview'),
    path('admin/boutique/<uuid:pk>/photo/',s.image_upload,name='shop-image-upload'),
    path('admin/boutique/photo/<uuid:pk>/',s.image_update,name='shop-image-update'),
]
