"use client";
import {useEffect,useRef,useState} from "react";import {motion} from "framer-motion";import gsap from "gsap";import * as THREE from "three";
const offers=[{tag:"Nouveau",title:"YVEXOR AI",copy:"Votre entreprise. Maintenant augmentée.",price:"Dès 350 € HT",theme:"blue",glyph:"AI"},{tag:"YVEXOR POS",title:"Plus rapide au comptoir.",copy:"Encaissement, stock et pilotage. Enfin simples.",price:"Dès 49 € HT/mois",theme:"silver",glyph:"POS"},{tag:"Automatisation",title:"Le travail avance. Même sans vous.",copy:"Reliez vos outils et éliminez les tâches répétitives.",price:"Sur devis",theme:"dark",glyph:"FLOW"},{tag:"Web & PWA",title:"Une présence qui travaille.",copy:"Rapide, installable et pensée pour convertir.",price:"Dès 39 € HT/mois",theme:"cyan",glyph:"WEB"}];
const stories=[{title:"YVEXOR POS",copy:"Une caisse claire pour les commerces pressés.",metric:"−38% de temps en caisse",tone:"violet"},{title:"AI Core",copy:"L’intelligence de l’entreprise, dans un espace privé.",metric:"7 h gagnées / semaine",tone:"blue"},{title:"Hotel Flow",copy:"Du check-in à la chambre, sans friction.",metric:"24/7",tone:"cyan"},{title:"Digital Partner",copy:"Une équipe produit qui avance avec vous.",metric:"350 € HT / mois",tone:"black"}];
function YxCore(){const host=useRef<HTMLDivElement>(null);useEffect(()=>{if(!host.current||matchMedia("(prefers-reduced-motion:reduce)").matches)return;const el=host.current,s=new THREE.Scene(),c=new THREE.PerspectiveCamera(40,1,.1,100);c.position.z=4;const r=new THREE.WebGLRenderer({alpha:true,antialias:true});r.setPixelRatio(Math.min(devicePixelRatio,1.5));el.appendChild(r.domElement);const g=new THREE.Group();s.add(g);g.add(new THREE.Mesh(new THREE.IcosahedronGeometry(1.15,5),new THREE.MeshBasicMaterial({color:0x31d7ff,wireframe:true,transparent:true,opacity:.22})));const h=new THREE.Mesh(new THREE.TorusGeometry(1.55,.012,8,180),new THREE.MeshBasicMaterial({color:0x1479ff,transparent:true,opacity:.7}));h.rotation.x=1.1;g.add(h);const z=()=>{let w=el.clientWidth,q=el.clientHeight;r.setSize(w,q,false);c.aspect=w/q;c.updateProjectionMatrix()};z();let id=0;const t=()=>{g.rotation.y+=.0025;h.rotation.z+=.003;r.render(s,c);id=requestAnimationFrame(t)};t();addEventListener("resize",z);return()=>{cancelAnimationFrame(id);removeEventListener("resize",z);r.dispose();el.replaceChildren()}},[]);return <div className="yxCore" ref={host}/>}
export default function Home(){const[menu,setMenu]=useState(false),[sent,setSent]=useState(false);useEffect(()=>{navigator.serviceWorker?.register("/sw.js");const c=gsap.context(()=>gsap.from(".heroCopy>*",{opacity:0,y:24,duration:.8,stagger:.1}));return()=>c.revert()},[]);return <main><header className="topnav"><a className="brand" href="#top"><span>YX</span><b>YVEXOR</b></a><nav className={menu?"show":""}><a href="#solutions">Solutions</a><a href="#tarifs">Tarifs</a><a href="#realisations">Réalisations</a><a href="#contact">Assistance</a></nav><a className="navCta" href="#contact">Nous contacter</a><button onClick={()=>setMenu(!menu)}>{menu?"×":"＝"}</button></header>
<section className="hero" id="top"><div className="aurora"/><YxCore/><div className="logoCrop"><img src="/yvexor-logo.jpeg" alt="Logo YVEXOR"/></div><div className="heroCopy"><span>YVEXOR 2026</span><h1>L’avenir.<br/>Déjà au travail.</h1><p>IA, logiciels et automatisation pour les entreprises qui veulent aller plus vite.</p><div className="actions"><a className="pill fill" href="#solutions">Découvrir</a><a className="pill line" href="#contact">Parler à YVEXOR</a></div></div></section>
<div className="promo">Un projet clair, un prix annoncé, un interlocuteur humain. <a href="#tarifs">Voir les tarifs ›</a></div>
<section className="offers" id="solutions">{offers.map(o=><motion.article className={`offer ${o.theme}`} key={o.tag} initial={{opacity:0,y:30}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.2}}><div className="offerCopy"><span>{o.tag}</span><h2>{o.title}</h2><p>{o.copy}</p><div className="actions"><a className="pill fill" href="#contact">En savoir plus</a><a className="buy" href="#contact">{o.price} ›</a></div></div><div className="window"><div className="dots"><i/><i/><i/></div><b>{o.glyph}</b><div className="scan"/></div></motion.article>)}</section>
<section className="why"><h2>Conçu pour être<br/><span>simplement puissant.</span></h2><div className="whyGrid"><article><b>2 s</b><h3>Chargement éclair</h3><p>Une interface immédiate, même sur mobile.</p></article><article><b>24/7</b><h3>Toujours disponible</h3><p>PWA installable et mode hors ligne.</p></article><article><b>1</b><h3>Partenaire unique</h3><p>Du cadrage au support, sans ping-pong.</p></article></div></section>
<section className="stories" id="realisations"><div className="sectionTitle"><h2>Découvrez ce que<br/>YVEXOR rend possible.</h2><p>Glissez pour explorer.</p></div><div className="rail">{stories.map(s=><article className={s.tone} key={s.title}><span>Étude de cas</span><h3>{s.title}</h3><p>{s.copy}</p><strong>{s.metric}</strong><a href="#contact">+</a></article>)}</div></section>
<section className="prices" id="tarifs"><h2>Choisissez votre<br/>point de départ.</h2><div className="priceRail"><article><span>Site professionnel</span><strong>39 €</strong><small>HT / mois</small><p>Design, hébergement, maintenance et SEO.</p><a className="pill fill" href="#contact">Choisir</a></article><article className="best"><span>Digital Partner</span><strong>350 €</strong><small>HT / mois</small><p>Développement continu et évolutions cadrées.</p><a className="pill fill" href="#contact">Choisir</a></article><article><span>Produit sur mesure</span><strong>5 400 €</strong><small>à l’achat</small><p>Conception, développement et formation.</p><a className="pill fill" href="#contact">Nous parler</a></article></div></section>
<section className="contact" id="contact"><div><img src="/yvexor-logo.jpeg" alt="YVEXOR"/><h2>Votre prochain<br/>grand projet.</h2><p>Expliquez-nous le résultat visé. Nous revenons vers vous avec une direction claire.</p><a href="tel:+33756913013">07 56 91 30 13</a></div><form onSubmit={e=>{e.preventDefault();setSent(true);e.currentTarget.reset()}}><input required placeholder="Nom"/><input required type="email" placeholder="E-mail"/><input required placeholder="Entreprise"/><select required defaultValue=""><option value="" disabled>Votre besoin</option><option>Site / PWA</option><option>IA / automatisation</option><option>YVEXOR POS</option><option>Sur mesure</option></select><textarea required placeholder="Parlez-nous du projet" rows={4}/><button className="pill fill">{sent?"Demande prête ✓":"Envoyer la demande"}</button></form></section>
<footer><div className="brand"><span>YX</span><b>YVEXOR</b></div><p>Technologie utile. Expérience radicalement claire.</p><nav><a href="#solutions">Solutions</a><a href="#tarifs">Tarifs</a><a href="#contact">Contact</a></nav><small>© 2026 YVEXOR</small></footer><div className="mobileBar"><a href="tel:+33756913013">Appeler</a><a href="#contact">Démarrer un projet</a></div></main>}
