import { monthlyServices } from "../data/budget-categories";
import { budgetGuidance } from "../data/public-offer";
import { ActionLink, SectionHeading } from "./ui";

export function BudgetSection() {
  return <section className="section budget-section" id="budgets">
    <SectionHeading eyebrow="Parler du budget" title="Votre budget doit aider à définir la première étape." intro="Vous avez déjà une enveloppe en tête ? Dites-la-nous. Nous regarderons quelle solution existante, quelle première version ou quel montage peut être cohérent."/>
    <div className="budget-grid budget-guidance-grid">{budgetGuidance.map((category, index) => <article className="budget-card" key={category.title}>
      <span>0{index + 1}</span><h3>{category.title}</h3><strong>{category.price}</strong><small className="budget-payment-note">{category.note}</small><p>{category.text}</p><span className="budget-badge">{category.badge}</span><a className="budget-card-link" href="#assistant">{category.cta} →</a>
    </article>)}</div>
    <div className="payment-value"><span>Valeur du projet ≠ somme à sortir aujourd’hui</span><h3>Le montant d’un projet ne signifie pas nécessairement qu’il doit être réglé ou développé entièrement dès le départ.</h3><p>Parlez-nous de votre besoin, du budget disponible aujourd’hui et de votre objectif. Selon le dossier et après accord, YVEXOR peut étudier plusieurs échéances, un développement par phases, une première version plus petite, une licence, un abonnement ou une formule hybride. Le travail conserve sa valeur : c’est son organisation qui peut être adaptée.</p></div>
    <div className="budget-foot"><p>Ces repères sont indicatifs et ne constituent pas un devis. Aucune modalité de paiement n’est automatique ; elle dépend du projet et d’une validation YVEXOR.</p><ActionLink href="#assistant" className="primary">Parler de mon budget</ActionLink></div>
    <aside className="idea-launch"><div><span>Vous avez une idée à lancer ?</span><h3>Testons l’usage avant de construire la version complète.</h3><p>Application, SaaS, marketplace ou nouveau service numérique : nous pouvons commencer par un cadrage, un prototype, un MVP et de premiers utilisateurs avant de faire évoluer le produit.</p><p>Sur certains projets présentant un potentiel et un modèle économique réels, une organisation commerciale spécifique ou un partenariat peut être étudié.</p><small>Cette possibilité reste exceptionnelle, soumise à l’étude et à la validation YVEXOR, ainsi qu’à un contrat précisant investissements, responsabilités, propriété intellectuelle, revenus, durée et sortie. YVEXOR reste votre partenaire technologique, pas un incubateur ni un établissement de crédit.</small></div><ActionLink href="#assistant" className="secondary">Présenter mon idée</ActionLink></aside>
    <div className="monthly" id="services-mensuels"><div className="monthly-intro"><p className="eyebrow">Et après la mise en service ?</p><h3>Des services mensuels, seulement lorsqu’ils sont utiles.</h3><p>Selon le projet, ils peuvent concerner l’hébergement, les sauvegardes, la maintenance, les API, l’infrastructure, les services connectés ou le support.</p></div><div className="monthly-list">{monthlyServices.map(service => <div key={service.title}><span>{service.title}</span><strong>{service.price}</strong></div>)}</div><small>Le contenu exact est défini dans chaque proposition YVEXOR.</small></div>
  </section>;
}
