import catalogue from "../data/caisses.json";
import {professions,caisseFaq,type Profession} from "../data/caisse-professions";
import {SiteHeader,MobileTabBar} from "./navigation";
import {SiteFooter} from "./site-footer";
import {PageData} from "./structured-data";
import {CaisseConfigurator,CaisseSelectLink} from "./caisse-configurator";
import styles from "./caisse.module.css";
export function CaissePage({profession,local=false}:{profession?:Profession;local?:boolean}){
 const family=profession?.family??"commerce",title=local?"Votre caisse de commerce à Marseille":profession?.title??"Une caisse adaptée à votre métier.";
 const path=local?"/logiciel-caisse-marseille/":profession?`/caisse/${profession.slug}/`:"/caisse/";
 const description=local?"Configurez votre caisse à Marseille : Essentiel, Stock ou Pilotage, matériel compatible ou poste YVEXOR. Préparez votre demande et une démonstration.":profession?.intro??"Découvrez YVEXOR Caisses : commerce, snack, coiffure et beauté. Comparez les formules, utilisez votre matériel ou choisissez un poste YVEXOR.";
 return <><SiteHeader root/><PageData path={path} title={title} description={description} service="YVEXOR Caisses" faq={caisseFaq}/><main id="contenu" className={styles.page}>
 <section className="cx-hero" id="accueil"><nav className="cx-breadcrumb" aria-label="Fil d’Ariane"><a href="/">Accueil</a><span>/</span>{profession||local?<><a href="/caisse/">Caisses</a><span>/</span><span aria-current="page">{local?"Marseille":profession?.name}</span></>:<span aria-current="page">Caisses</span>}</nav><div className="cx-hero-grid"><div><p className="eyebrow">YVEXOR CAISSES · {profession?.name??"Un écosystème, votre métier"}</p><h1>{title}</h1><p className="cx-lead">{profession?profession.intro:"Utilisez votre propre matériel ou équipez-vous avec YVEXOR."}</p>{!profession&&<p>Une base commune, configurée pour votre activité. Le logiciel chaque mois, le matériel seulement si vous en avez besoin.</p>}<a className="action-link primary" href={profession?"#configurateur":"#activites"}>{profession?"Configurer ma solution":"Trouver ma solution"} →</a></div><figure><img src={`/${family==="snack"?"solution-restaurant-v1.webp":family==="salon"?"solution-logiciel-v1.webp":"solution-commerce-v1.webp"}`} width="960" height={family==="snack"?1440:640} alt="" fetchPriority="high"/><figcaption>Illustration d’un environnement métier · matériel et fonctions selon configuration.</figcaption><span className="cx-image-label">Votre métier.<br/><strong>Votre configuration.</strong></span></figure></div></section>
 <nav className="cx-subnav" aria-label="Dans la gamme Caisses"><a href="#activites">Activités</a><a href="#tarifs">Formules</a><a href="#equipement">Matériel</a><a href="#configurateur">Configurer</a><a href="#questions">Questions</a></nav>
 <section className="cx-section" id="activites"><p className="eyebrow">Choisissez votre activité</p><h2>Un même écosystème. Cinq points de départ.</h2><div className="cx-families">{catalogue.families.map((f,i)=><a className="cx-family" href={f.href} key={f.id}><span className="cx-index">0{i+1}</span><h3>{f.name}</h3><p>{f.description}</p><strong>{f.startingPrice?`À partir de ${f.startingPrice} € HT / mois`:f.id==="restaurant"?"Découvrir Restaurant OS →":"Parler de mon activité →"}</strong></a>)}</div><details className="cx-professions" open={!!profession&&family==="commerce"}><summary>Voir les métiers du commerce et de la beauté</summary><div>{professions.filter(p=>!["commerce","snack","autre"].includes(p.slug)).map(p=><a href={`/caisse/${p.slug}/`} aria-current={profession?.slug===p.slug?"page":undefined} key={p.slug}>{p.name} →</a>)}</div></details></section>
 {profession&&<section className="cx-section cx-focus"><p className="eyebrow">Votre quotidien</p><h2>{profession.name} : partons de ce qui compte.</h2><div className="cx-focus-grid">{profession.focus.map((f,i)=><article key={f}><span className="cx-index">0{i+1}</span><h3>{f}</h3></article>)}</div><p className="cx-note">{profession.check}</p></section>}
 {local&&<section className="cx-section"><h2>Préparons une démonstration avec votre matériel.</h2><p>À Marseille, dans les Bouches-du-Rhône ou à distance, transmettez votre type de commerce, votre catalogue et les modèles de vos périphériques. La reprise de données et une intervention sur place se définissent au devis, sans zone d’intervention ni délai garanti par défaut.</p></section>}
 <section className="cx-section" id="tarifs"><span id="tarifs-caisse"/><p className="eyebrow">Logiciel · abonnement mensuel</p><h2>{family==="salon"?"Votre salon, dans un même espace.":family==="other"?"Le bon périmètre avant le bon prix.":"Encaisser. Suivre. Comprendre."}</h2><p>{family==="other"?"Votre activité fera l’objet d’une proposition personnalisée.":"Des niveaux lisibles, à confirmer en démonstration et au devis. Aucun achat de matériel imposé."}</p><div className="cx-plans">{catalogue.plans.filter(p=>p.families.includes(family)).map(p=><article key={p.id} className={`cx-plan ${p.recommended?"cx-recommended":""}`}>{p.recommended&&<span className="cx-badge">Recommandé pour le suivi des produits</span>}<h3>{p.name}</h3><p className="cx-price">{p.monthly} € <small>HT / mois</small></p><p>{p.description}</p><ul>{p.features.map(f=><li key={f}>{f}</li>)}</ul><p className="cx-small">{p.exclusion}</p><CaisseSelectLink values={{plan:p.id}}>Choisir {p.name} →</CaisseSelectLink></article>)}</div>
 {family!=="other"&&<details className="cx-comparison"><summary>Comparer les périmètres et les fonctions à valider</summary><p>Le socle d’encaissement et l’historique existent dans YVEXOR POS. Cet audit du site ne certifie pas les modules métier ci-dessous : la démonstration confirme leur disponibilité sur votre version.</p><div className="cx-focus-grid"><article><h3>Encaissement</h3><p>Articles, catégories, TVA, tickets et historique. À vérifier : espèces / carte / paiement mixte, remises, retour, annulation selon droits, scanner et iPhone.</p></article><article><h3>{family==="salon"?"Rendez-vous":"Stock"}</h3><p>{family==="salon"?"Agenda, disponibilité, choix de prestation et page de réservation prévus dans l’offre. Raccordement, modification et annulation à confirmer.":"Absent d’Essentiel. Stock et Pilotage visent quantités, entrées/sorties, inventaires, mouvements et alertes. Fournisseurs et recettes automatiques non confirmés."}</p></article><article><h3>{family==="salon"?"Clients":"Pilotage"}</h3><p>{family==="salon"?"Fiches, coordonnées et historique de prestations prévus. Notes internes et historique de rendez-vous à valider.":"Pilotage vise prix d’achat, marges article/catégorie/globales, rentabilité et exports pour votre comptabilité. Dépenses et rapports avancés à confirmer."}</p></article></div></details>}</section>
 <section className="cx-section" id="equipement"><p className="eyebrow">Le matériel, séparément</p><h2>Gardez le vôtre. Ou choisissez le nôtre.</h2><div className="cx-hardware">{catalogue.hardware.map(h=><article key={h.id}><h3>{h.name}</h3><p className="cx-price">{h.once} € <small>HT · achat unique{h.once===0?" de poste YVEXOR":""}</small></p><p>{h.description}</p><CaisseSelectLink values={{hardware:h.id}}>{h.id==="own"?"Utiliser mon matériel":"Choisir un poste YVEXOR"} →</CaisseSelectLink></article>)}</div><p className="cx-note">Ordinateur, tablette, smartphone, imprimante ou écran : vérification de compatibilité nécessaire. Le poste à 380 € n’est ni une licence logicielle ni une borne de commande. Installation et configuration sont précisées séparément.</p></section>
 {family==="snack"&&<section className="cx-section"><p className="eyebrow">Des options distinctes</p><h2>Une commande peut commencer à plusieurs endroits.</h2><ol className="cx-flow"><li>Le client scanne un QR</li><li>Menu et suppléments</li><li>Validation · paiement si activé</li><li>Caisse et cuisine, après raccordement</li></ol><p>Ce parcours décrit la cible du module mobile. Les transmissions automatiques et l’absence de ressaisie doivent être validées avant activation. Une borne suit un parcours similaire sur un écran dédié.</p><div className="cx-focus-grid">{catalogue.options.filter(o=>o.id!=="website").map(o=><article key={o.id}><h3>{o.name}</h3><p className="cx-price">+{o.monthly} € <small>HT / mois{o.unit!=="module"?` / ${o.unit}`:""}</small></p><p>{o.description}</p><span className="cx-status">{o.availability}</span></article>)}</div><details><summary>Le parcours prévu en cuisine</summary><p>Nouvelles commandes, à préparer, en préparation, prêtes : numéro, horaire, produits, options et commentaires. L’origine caisse, mobile ou borne sera affichée après raccordement. Stations possibles : cuisine, bar, desserts ou retrait. Gestion automatique des recettes non confirmée.</p></details></section>}
 {family!=="other"&&<section className="cx-section cx-website"><p className="eyebrow">Option présence web</p><h2>Votre activité mérite aussi sa vitrine.</h2><p className="cx-price">+{catalogue.options[0].monthly} € <small>HT / mois</small></p><p>{family==="salon"?"Un site complet peut présenter le salon, l’équipe, les prestations, les tarifs, une galerie, les horaires et le contact. Il est distinct de la page de réservation prévue dans l’offre Salon à 60 € HT/mois.":family==="snack"?"Présentez l’établissement, le menu, les horaires et les nouveautés. Le site à 39 € et la commande mobile à 29 € sont deux modules différents, combinables.":"Présentez votre commerce, vos horaires, vos coordonnées et vos nouveautés. Un catalogue peut être étudié lorsqu’il est connecté à vos données."}</p><p className="cx-small">Pas d’e-commerce, de livraison, de domaine gratuit ou de référencement avancé automatiquement inclus. Contenus, hébergement et raccordements précisés au devis.</p><CaisseSelectLink values={{website:true}}>Ajouter un site à ma configuration →</CaisseSelectLink></section>}
 <CaisseConfigurator profession={profession?.slug??"commerce"}/>
 <section id="questions" className="cx-section"><h2>Vos questions, avant de choisir.</h2>{caisseFaq.map(q=><details className="cx-faq" key={q.title}><summary>{q.title}</summary><p>{q.text}</p></details>)}</section>
 <section className="cx-section cx-final" id="projet"><h2>Testons votre façon de travailler.</h2><p>Une démonstration, vos produits, vos équipements. Nous confirmons ensemble ce qui est disponible et ce qui nécessite une adaptation.</p><a className="action-link primary" href="#configurateur">Préparer ma demande →</a></section>
 </main><SiteFooter/><MobileTabBar root/></>
}
