import { SmsLink } from "./sms-link";

const plans = [
  {name:"Encaisser",price:29,description:"Une première caisse pour un petit commerce à un seul poste.",items:["Encaissement et tickets","Suivi du chiffre d’affaires et historique","Gestion de stock non incluse"]},
  {name:"Gérer",price:79,description:"Passez de l’encaissement au suivi quotidien de votre activité.",items:["Encaissement et gestion de stock","Inventaire et alertes","Première fonction métier définie dans le devis"]},
  {name:"Piloter",price:129,description:"Une organisation plus complète, adaptée à votre métier.",items:["Fonctions de gestion et fournisseurs","Fidélité selon la configuration","Équipe ou planning selon le périmètre retenu"]},
];
export function CommercePricing(){return <section className="section commerce-pricing" id="tarifs-caisse" aria-labelledby="commerce-pricing-title">
  <p className="eyebrow">Votre caisse, à votre rythme</p><h2 id="commerce-pricing-title">Encaisser. Gérer. Piloter.</h2><p>Commencez par l’essentiel, puis faites évoluer votre solution selon votre activité.</p>
  <div className="commerce-plans">{plans.map(plan=><article className="commerce-plan" key={plan.name}><h3>{plan.name}</h3><p className="commerce-price"><span>À partir de</span><strong>{plan.price} €</strong><span>HT / mois</span></p><p>{plan.description}</p><ul>{plan.items.map(item=><li key={item}>{item}</li>)}</ul><SmsLink className="action-link primary">Étudier cette formule</SmsLink></article>)}</div>
  <div className="commerce-terms"><h3>Votre métier fait la différence.</h3><p>Boutique : codes-barres et inventaire. Salon : rendez-vous et produits. Garage : pièces et atelier. Boulangerie : précommandes et suivi des produits. Ces exemples sont étudiés selon les fonctions disponibles, les adaptations et les connexions nécessaires.</p><h3>Un projet plus spécifique ? Sur devis.</h3><p>Multi-sites, bornes, équipements connectés, automatisations ou IA : nous définissons ensemble le périmètre utile. Une licence perpétuelle peut également être étudiée, avec les services associés précisés séparément.</p><p>Prix de départ, pas un forfait couvrant toutes les possibilités : les activités plus exigeantes peuvent démarrer à 49 € HT/mois ou davantage. Le devis confirme les fonctions, postes, utilisateurs, assistance, maintenance et conditions d’engagement.</p><p>Matériel, installation, configuration, reprise de données, développements spécifiques et éventuels services tiers sont chiffrés séparément selon le besoin. L’abonnement ne représente donc pas nécessairement la totalité du montant à prévoir au démarrage.</p><SmsLink className="action-link secondary">Trouver la formule adaptée à mon commerce</SmsLink></div>
 </section>}
