// Local-only browser smoke test. Never point this script at a deployed service.
const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const path = require('node:path');
(async () => {
  const browser = await chromium.launch({headless:true, channel:process.env.PORTAL_TEST_BROWSER || 'msedge'});
  const page = await browser.newPage({viewport:{width:1440,height:1000}});
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('http://127.0.0.1:8181/auth/signup/');
  await page.locator('#id_first_name').fill('Test local');
  await page.locator('#id_last_name').fill('Navigation');
  await page.locator('#id_email').fill(`local-${Date.now()}@example.invalid`);
  assert.equal(await page.locator('#id_phone, #id_company, #id_password2').count(), 0);
  await page.locator('#id_password1').fill('OnlyLocalPreview!2026');
  await page.getByRole('button', {name:'Afficher le mot de passe'}).click();
  assert.equal(await page.locator('#id_password1').getAttribute('type'), 'text');
  await page.getByRole('button', {name:'Masquer le mot de passe'}).click();
  await page.getByRole('button', {name:'Créer mon compte'}).click();
  await page.waitForURL('**/client/');
  await page.screenshot({path:path.join(__dirname,'private','client-desktop.png'),fullPage:true});
  await page.goto('http://127.0.0.1:8181/requests/new/');
  await page.locator('#id_title').fill('Demande de test navigateur');
  await page.locator('#id_body').fill('Vérification locale du formulaire et de sa confirmation.');
  await page.getByRole('button', {name:'Vérifier ma demande'}).click();
  await page.getByRole('button', {name:'Envoyer ma demande'}).click();
  await page.waitForURL(/\/requests\/[0-9a-f-]+\/$/);
  await page.getByLabel('Votre message', {exact:false}).fill('Message de test local.');
  await page.getByRole('button', {name:'Envoyer le message'}).click();
  await page.getByText('Message de test local.', {exact:true}).waitFor();
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:path.join(__dirname,'private','request-mobile.png'),fullPage:true});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'Mobile overflow');
  await page.goto('http://127.0.0.1:8181/client/');
  await page.screenshot({path:path.join(__dirname,'private','client-mobile.png'),fullPage:true});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'Dashboard overflow');
  await page.goto('http://127.0.0.1:8181/account/');
  await page.getByRole('button',{name:'Se déconnecter de cet appareil'}).click();
  await page.waitForURL('**/auth/login/');
  assert.deepEqual(errors,[]);
  console.log('Browser smoke passed: signup, request review/send, message, mobile layout, logout.');
  await browser.close();
})().catch(error=>{console.error(error);process.exit(1)});
